from .criteria import CriteriaAPIView
from .criteria_detail import CriteriaDetailAPIView
from .criteria_template import CriteriaTemplateAPIView
from .criteria_template_detail import CriteriaTemplateDetailAPIView